export const PROFILE_TYPE_FIELDS = {
  developer: [
    { name: 'specialization', label: 'Specialization', type: 'select',
      options: ['Game Developer','Engine Programmer','Technical Artist','DevOps','QA Engineer','Producer'], required: true },
    { name: 'experience_years', label: 'Years of Experience', type: 'number', min: 0, max: 50 },
    { name: 'primary_engine', label: 'Primary Engine', type: 'select',
      options: ['Unreal Engine 5','Unity','Godot','Custom Engine','GameMaker','Other'] },
    { name: 'languages', label: 'Programming Languages', type: 'text', placeholder: 'C++, Python, Rust...' },
    { name: 'portfolio_url', label: 'Portfolio / GitHub', type: 'url', placeholder: 'https://github.com/...' },
    { name: 'availability', label: 'Availability', type: 'select',
      options: ['Full-time','Part-time','Contract','Freelance','Not available'] },
    { name: 'rate_per_hour', label: 'Hourly Rate (USD)', type: 'number', min: 0, placeholder: 'Optional' },
  ],
  esports: [
    { name: 'esports_role', label: 'Primary Role', type: 'select', required: true,
      options: ['Professional Player', 'Esports Coach', 'Esports Analyst', 'Shoutcaster / Commentator', 'AI Match Referee', 'Esports Data Scientist', 'Fan Engagement Engineer', 'Esports Integrity Officer'] },
    { name: 'coaching_availability', label: 'Available for Coaching?', type: 'checkbox' },
    { name: 'coaching_rate', label: 'Coaching Rate (USD/hr)', type: 'number', placeholder: 'Optional' },
    { name: 'coaching_specialty', label: 'Coaching Specialty Games', type: 'text', placeholder: 'Valorant, CS2...' },
    { name: 'streaming_url', label: 'Stream / VOD Channel', type: 'url' },
  ],
  content: [
    { name: 'content_role', label: 'Primary Role', type: 'select', required: true,
      options: ['Streamer', 'Gaming YouTuber', 'Video Producer / Editor', 'Gaming Podcaster', 'Influencer / Brand Ambassador', 'Game Journalist', 'Community Manager', 'Social Media Manager', 'Marketing Specialist', 'Public Relations Manager', 'Event Manager', 'Partnership Manager'] },
    { name: 'content_niche', label: 'Content Niche Tags', type: 'multiselect',
      options: ['FPS', 'RPG', 'Horror', 'Mobile', 'Esports commentary', 'Educational', 'Variety', 'IRL', 'Battle Royale', 'Retro', 'Speedrunning', 'Tech/Hardware'] },
    { name: 'posting_frequency', label: 'Posting Frequency', type: 'select',
      options: ['Daily', '3-5x per week', 'Weekly', 'Bi-weekly', 'Monthly'] },
  ],
  artist: [
    { name: 'art_discipline', label: 'Art Discipline', type: 'select',
      options: ['Concept Artist','3D Modeler','Character Artist','Environment Artist','UI/UX Designer',
                'Motion Designer','Illustrator','Texture Artist'], required: true },
    { name: 'software', label: 'Software / Tools', type: 'text', placeholder: 'Blender, ZBrush, Photoshop...' },
    { name: 'portfolio_url', label: 'Portfolio URL', type: 'url', required: true },
    { name: 'art_style', label: 'Art Style', type: 'text', placeholder: 'Stylized, Photorealistic, Pixel Art...' },
    { name: 'availability', label: 'Availability', type: 'select',
      options: ['Full-time','Part-time','Contract','Freelance','Not available'] },
    { name: 'commission_rates_public', label: 'Show Commission Rates Publicly', type: 'checkbox' },
  ],
  writer: [
    { name: 'writing_role', label: 'Primary Role', type: 'select', required: true,
      options: ['Game Writer', 'Narrative Designer', 'Localization Writer', 'AI Narrative Generator', 'Emotional Experience Designer', 'Game Journalist', 'Technical Writer', 'Worldbuilding Specialist', 'Educational Game Designer'] },
    { name: 'writing_genres', label: 'Writing Genres / Types', type: 'multiselect',
      options: ['Narrative', 'Editorial/Journalism', 'Technical writing', 'Creative writing', 'Educational', 'Worldbuilding', 'Review/criticism', 'Blog', 'Scriptwriting', 'Dialogue'] },
    { name: 'languages_written', label: 'Languages Written In', type: 'multiselect',
      options: ['English', 'Hindi', 'Spanish', 'French', 'German', 'Japanese', 'Korean', 'Portuguese', 'Arabic', 'Mandarin', 'Other'] },
    { name: 'portfolio_url', label: 'Writing Portfolio / Blog', type: 'url' },
  ],
  audio: [
    { name: 'audio_role', label: 'Primary Role', type: 'select', required: true,
      options: ['Sound Designer', 'Composer', 'Audio Engineer', 'Voice Actor', 'Foley Artist', 'Adaptive Audio Designer'] },
    { name: 'audio_speciality', label: 'Audio Speciality Tags', type: 'multiselect',
      options: ['Ambient', 'Orchestral', 'Electronic', 'Chiptune', 'SFX', 'Voice Acting', 'Foley', 'Adaptive/Interactive audio', 'Music theory', 'Mixing/Mastering', 'Scoring'] },
    { name: 'daw_proficiency', label: 'DAWs Used', type: 'multiselect',
      options: ['Ableton', 'FL Studio', 'Logic Pro', 'Pro Tools', 'Reaper', 'Cubase', 'GarageBand', 'FMOD', 'Wwise', 'Nuendo'] },
    { name: 'voice_acting_range', label: 'Voice Acting Range', type: 'multiselect',
      options: ['Narration', 'Character', 'Commercial', 'Animation', 'Anime dub'],
      showIf: { field: 'audio_role', value: 'Voice Actor' } },
    { name: 'licensing_model', label: 'Licensing Model for Tracks', type: 'select',
      options: ['Buyout', 'Royalty-free (single use)', 'Subscription', 'Custom licensing'] },
    { name: 'samples_available', label: 'Samples Available for Request', type: 'checkbox' },
    { name: 'portfolio_url', label: 'Demo Reel / Portfolio', type: 'url' },
  ],
  business: [
    { name: 'business_role', label: 'Primary Role', type: 'select', required: true,
      options: ['Game Producer', 'Project Manager', 'Game Publisher', 'Business Development Manager', 'Licensing Specialist', 'Investor / Entrepreneur', 'Digital Asset Economist', 'Gaming Lawyer', 'Virtual Property Rights Specialist', 'Chief Metaverse Officer'] },
    { name: 'industry_sector', label: 'Industry Sector', type: 'select',
      options: ['Publisher', 'Studio', 'Startup', 'Agency', 'Legal', 'Finance', 'Investment', 'Policy', 'Consultancy'] },
    { name: 'company_name', label: 'Current Company', type: 'text' },
    { name: 'company_size_range', label: 'Company Size', type: 'select',
      options: ['Indie (<10)', 'SME (10-200)', 'Enterprise (200+)'] },
    { name: 'deal_types_completed', label: 'Deal Types Completed', type: 'multiselect',
      options: ['Publishing deal', 'Licensing', 'Investment', 'M&A', 'Partnership', 'Legal advisory', 'Distribution'] },
    { name: 'linkedin_url', label: 'LinkedIn Profile', type: 'url', placeholder: 'https://linkedin.com/in/...' },
    { name: 'speaking_history', label: 'Speaking / Conferences', type: 'textarea',
      placeholder: 'GDC 2024 – "Monetisation Models in Indie Games"\nNasscom 2023...' },
    { name: 'verified_linkedin', label: 'Show LinkedIn Verified Badge', type: 'checkbox' },
  ],
};
